apiVersion: v1
kind: PersistentVolume
metadata:
  name: forgejo-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/saturn-cicd/forgejo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-pv-claim
  namespace: saturn-cicd
  labels:
    app: forgejo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo
  namespace: saturn-cicd
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: forgejo
  template:
    metadata:
      labels:
        app: forgejo
    spec:
      securityContext:      
        fsGroup: 5000
      containers:
      - name: forgejo
        image: codeberg.org/forgejo/forgejo:14
        ports:
        - containerPort: 3000
        - containerPort: 22
        env:
        - name: USER_UID
          value: "969"
        - name: USER_GID
          value: "5000"
        - name: FORGEJO__server__SSH_PORT
          value: "2222"
        - name: FORGEJO__server__ROOT_URL
          value: https://saturn:30088/cicd/forgejo/
        - name: FORGEJO__database__DB_TYPE
          value: postgres
        - name: FORGEJO__database__HOST
          value: postgres-service
        - name: FORGEJO__database__NAME
          value: forgejo  
        - name: FORGEJO__database__USER
          valueFrom:
            secretKeyRef:
              name: postgres-user-pass
              key: username
        - name: FORGEJO__database__PASSWD
          valueFrom:
            secretKeyRef:
              name: postgres-user-pass
              key: password
        - name: FORGEJO__mailer__ENABLED
          value: "true"
        - name: FORGEJO__mailer__PROTOCOL
          value: "smtp"
        - name: FORGEJO__mailer__SMTP_ADDR
          value: "192.168.0.133"
        - name: FORGEJO__mailer__SMTP_PORT
          value: "25"
        - name: FORGEJO__mailer__FROM
          value: "cicd-admin@saturn"
        - name: FORGEJO__webhook__ALLOWED_HOST_LIST
          value: "*"
        # - name: GITEA__webhook__ALLOWED_HOST_LIST
        #   value: "*"
        volumeMounts:
        - name: forgejo-persistent-storage
          mountPath: /data
      volumes:
      - name: forgejo-persistent-storage
        persistentVolumeClaim:
          claimName: forgejo-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: forgejo-service
  namespace: saturn-cicd
spec:
  selector:
    app: forgejo
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: agent
      protocol: TCP
      port: 2222
      targetPort: 22
---
apiVersion: networking.k8s.io/v1 # Note: Standardizing for your version
kind: Ingress
metadata:
  name: forgejo-ingress
  namespace: saturn-cicd
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  # - host: 192.168.0.133
  - http:
      paths:
      - path: /cicd/forgejo(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: forgejo-service
            port:
              number: 3000