apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
spec:
  capacity:
    storage: 150Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/saturn-cicd-sec/jenkins
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  namespace: saturn-cicd
  labels:
    app: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: saturn-cicd
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        runAsUser: 970
        runAsGroup: 5000
        fsGroup: 5000
        supplementalGroups: [975]
      containers:
      - name: jenkins
        image: jenkins/jenkins:2.580-jdk25
        ports:
        - containerPort: 8080
        - containerPort: 50000
        env:
        - name: JENKINS_OPTS
          value: "--prefix=/cicd/jenkins"
        volumeMounts:
        - name: jenkins-persistent-storage
          mountPath: /var/jenkins_home
        - name: docker-sock
          mountPath: /var/run/docker.sock  
        readinessProbe:
          httpGet:
            path: /cicd/jenkins/login
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 10  
      volumes:
      - name: jenkins-persistent-storage
        persistentVolumeClaim:
          claimName: jenkins-pv-claim
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: saturn-cicd
spec:
  selector:
    app: jenkins
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: agent
      protocol: TCP
      port: 50000
      targetPort: 50000
---
apiVersion: networking.k8s.io/v1 # Note: Standardizing for your version
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: saturn-cicd
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  # - host: 192.168.0.133
  - http:
      paths:
      - path: /cicd/jenkins
        pathType: Prefix
        backend:
          service:
            name: jenkins-service
            port:
              number: 8080