apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv
spec:
  capacity:
    storage: 400Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/saturn-cicd/nexus
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pv-claim
  namespace: saturn-cicd
  labels:
    app: nexus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: saturn-cicd
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      securityContext:
        runAsUser: 200
        runAsGroup: 5000
        fsGroup: 5000
      containers:
      - name: nexus
        image: sonatype/nexus3:3.89.0
        ports:
        - containerPort: 8081
        - containerPort: 8082
        env:
        - name: NEXUS_CONTEXT
          value: cicd/nexus/
        volumeMounts:
        - name: nexus-persistent-storage
          mountPath: /nexus-data
        readinessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 10  
      volumes:
      - name: nexus-persistent-storage
        persistentVolumeClaim:
          claimName: nexus-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: saturn-cicd
spec:
  selector:
    app: nexus
  ports:  
    - name: nexus-ui
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: docker-reg
      protocol: TCP
      port: 8082
      targetPort: 8082
---
apiVersion: networking.k8s.io/v1 # Note: Standardizing for your version
kind: Ingress
metadata:
  name: nexus-ingress
  namespace: saturn-cicd
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "2000m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  # - host: 192.168.0.133
  - http:
      paths:
      - path: /cicd/nexus
        pathType: Prefix
        backend:
          service:
            name: nexus-service
            port:
              number: 8081
      - path: /v2  
        pathType: Prefix
        backend:
          service:
            name: nexus-service
            port:
              number: 8082