apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-mongo-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/saturn-backend/mongo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-mongo-pv-claim
  namespace: saturn-backend
  labels:
    app: mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: saturn-backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      securityContext:
        runAsUser: 965
        runAsGroup: 5002
        fsGroup: 5002
      containers:
      - name: mongo
        image: mongo:8.3.11
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-user-pass
              key: password
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-user-pass
              key: username
        volumeMounts:
        - name: backend-mongo-persistent-storage
          mountPath: /data/db
      volumes:
      - name: backend-mongo-persistent-storage
        persistentVolumeClaim:
          claimName: backend-mongo-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: saturn-backend
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
