apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-valkey-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/saturn-backend/valkey
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-valkey-pv-claim
  namespace: saturn-backend
  labels:
    app: valkey
spec:
  volumeName: backend-valkey-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  namespace: saturn-backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      securityContext:
        runAsUser: 965
        runAsGroup: 5002
        fsGroup: 5002
      containers:
      - name: valkey
        image: valkey/valkey:9.1
        command:
          - valkey-server
          - --requirepass
          - $(VALKEY_PASSWORD)
          - --save
          - "60"
          - "1"
          - --loglevel
          - debug
        ports:
        - containerPort: 6379
        env:
        - name: VALKEY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: valkey-user-pass
              key: password
        volumeMounts:
        - name: backend-valkey-persistent-storage
          mountPath: /data
        resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
      - name: backend-valkey-persistent-storage
        persistentVolumeClaim:
          claimName: backend-valkey-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: valkey-service
  namespace: saturn-backend
spec:
  selector:
    app: valkey
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
