apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-rabbitmq-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/saturn-backend/rabbitmq
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-rabbitmq-pv-claim
  namespace: saturn-backend
  labels:
    app: rabbitmq
spec:
  volumeName: backend-rabbitmq-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: saturn-backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      securityContext:
        runAsUser: 965
        runAsGroup: 5002
        fsGroup: 5002
      containers:
      - name: rabbitmq
        image: rabbitmq:4.3.6-management
        ports:
        - containerPort: 5672
        - containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_VHOST
          value: "saturn"
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-user-pass
              key: password
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-user-pass
              key: username
        volumeMounts:
        - name: backend-rabbitmq-persistent-storage
          mountPath: /var/lib/rabbitmq
      volumes:
      - name: backend-rabbitmq-persistent-storage
        persistentVolumeClaim:
          claimName: backend-rabbitmq-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: saturn-backend
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      name: tcp
      port: 5672
      targetPort: 5672
    - protocol: TCP
      name: http
      port: 15672
      targetPort: 15672
